server:
  port: 8082

spring:
  application:
    name: ytxy.heal
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/healthmanager?&serverTimezone=GMT%2B8&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false

      username: root
      password: word

  servlet:
    multipart:
      max-file-size: 5MB

  mvc:
    view:
      prefix: /pages/
      suffix: .html

  mybatis-plus:
    mapper-locations: mapper/*.xml
    type-aliases-package: org.example.entity
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





